services:
  - type: web
    name: pdf-stitcher-api
    env: docker
    plan: free
    buildCommand: docker build --platform linux/amd64 -t pdf-stitcher-api .
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5000"
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false 